### ISSUE TITLE
Add picture on index page

### ISSUE THREAD

**Issue by resyst-it** [tmaiaroto/hugo-redlounge#23]
Hello,
I like your theme but it's possible to add a function to add a small picture in front third ligne on the page where there are all post ?
This is an example with a french blog : http://blog.nicolargo.com/

Thanks.

**Comment by tmaiaroto** [comment]
Yes, but it'll take a little customization. Copy the template file from the theme and place it in your root layouts directory. This is the file you're going to copy: https://github.com/tmaiaroto/hugo-redlounge/blob/master/layouts/_default/list.html

You'll want to then alter the HTML to include the picture. It could even come from the optional banner image ```.Params.banner``` set in each markdown file. Or you can add a whole new variable to the front matter.

For more information see: https://gohugo.io/themes/customizing/#replace-a-single-template-file:0b8b0e4b5279f6824ca9414b485f6c4a

Also: https://gohugo.io/content/front-matter

**Comment by resyst-it** [comment]
Thanks,

Yes, i tried.

This is my post :

bannerinline = "../../img/docker.jpeg"

This is my modification on list.html :

<article class="post-summary">
                {{ .Params.bannerinline }}
                {{ .Summary }}
</article>

For me it's best place to insert a picture. But it's not ok.

Regards.



2015-12-03 6:34 GMT+01:00 Tom Maiaroto <notifications@github.com>:

> Yes, but it'll take a little customization. Copy the template file from
> the theme and place it in your root layouts directory. This is the file
> you're going to copy:
> https://github.com/tmaiaroto/hugo-redlounge/blob/master/layouts/_default/list.html
>
> You'll want to then alter the HTML to include the picture. It could even
> come from the optional banner image .Params.banner set in each markdown
> file. Or you can add a whole new variable to the front matter.
>
> For more information see:
> https://gohugo.io/themes/customizing/#replace-a-single-template-file:0b8b0e4b5279f6824ca9414b485f6c4a
>
> Also: https://gohugo.io/content/front-matter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmaiaroto/hugo-redlounge/issues/23#issuecomment-161521939>
> .
>



-- 
Florian CAUZARD-JARRY
1 rue des Brouets
78711 Mantes la Ville
06-71-71-04-80
