### ISSUE TITLE
A single page is always showing up home page list even though it's not located in the post directory

### ISSUE THREAD

**Issue by wiziah** [tmaiaroto/hugo-redlounge#24]
I have an about page which doesn't get listed on the blog page listing but appears on the home page listing. About menu link works fine. I think it has something to do with page types / sections in layouts?

![image](https://cloud.githubusercontent.com/assets/10791242/11092158/3582b200-88d5-11e5-88b5-fc4dd997347a.png)

**Comment by tmaiaroto** [comment]
Yes, all pages get listed on the main index page with Hugo. The blog section is looking at a specific archetype.

What I did as a workaround was add a ```public/about/index.html``` file and put in a whole new page independent of Hugo. It doesn't load the layout template or anything like that. Though I did copy the rendered page from elsewhere and just replaced the middle section. This way the sidebar was still there, etc. However, should that sidebar update...Then this static HTML page would also need to be updated. Not ideal if your site changes around a bit, but it's a workaround.
