### ISSUE TITLE
How I can to reduce quantity of symbols at the main page?

### ISSUE THREAD

**Issue by greendruid** [tmaiaroto/hugo-redlounge#25]
Hello!

Thanks for user-fiendly template for Gohugo! :-) I have a little question: how I can to reduce quantity of symbols at the main (first) page in the preview-block? Now It's a full-lenght 3 lines.... May I to cut this?

With best regards,
greedruid

**Comment by greendruid** [comment]
Solution: need use a tag "

**Comment by tmaiaroto** [comment]
Yup, you can modify this with specific overrides. The template uses ```.Summary``` which is generated automatically by Hugo. See: https://gohugo.io/content/summaries/

**Comment by greendruid** [comment]
2 tmaiaroto
Thank you! It's very usable :)
