### ISSUE TITLE
Social Menu and Disqus not working

### ISSUE THREAD

**Issue by Skarlso** [tmaiaroto/hugo-redlounge#27]
Hi!

First off, happy new year!

I'm trying to enable Social menu on the sidebar and disqus on my blog. 

Here is the blog => https://skarlso.github.io

If you look at the source, you can see that there is a div containing my site URL => skarlso.com. Which is nice, but it isn't visible for some reason. :) 

And then disqus. I set up the disqusShortname but nothing is happening. I do have a disqus account and shortname and everything, but I'm guessing I need something more? 

Here is my configuration file:

```
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://skarlso.github.io/"
title = "Ramblings of a build engineer"
canonifyurls = true

[taxonomies]
    category = "categories"
    tag = "tags"
[params]
    sidebartitle = "Ramblings..."
    sidebartagline = "...of a build engineer."
    highlightStyle = "true"
    disqusShortname = "mydisqusshortname"

[[menu.social]]
     pre = "<i class='fa fa-fort-awesome'></i>"
     url = "http://skarlso.com"
     identifier = "site" <- I tried everything here 
```

That's it. Any help is much appreciated! :+1: Thanks!

**Comment by tmaiaroto** [comment]
```<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">```

You'll need 4.5 as the icon you're using was added in that version. Simply switch 4.2 to 4.5...In fact I just made a quick edit to the theme so you can pull a new version.

As for Disqus, is that your complete ```config.toml``` file? I don't see ```disqusShortname = "value"``` in there. Disqus seems to work fine for me so I can't really reproduce the issue.

**Comment by Skarlso** [comment]
Hi @tmaiaroto. 

Excellent! Thanks!

As for Disqus... It's right there in [param].

```disqusShortname = "mydisqusshortname"```

**Comment by tmaiaroto** [comment]
Should be above ```[params]``` right along with ```baseurl``` and ```title``` etc.

**Comment by Skarlso** [comment]
Damn it! For some reason I assumed it should be in param... :) 

Thank you! Everything works nice and smoothly. :) Cheers man. And a happy new year!
