### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by mubix** [tmaiaroto/hugo-redlounge#37]
Not sure how to use this:

https://github.com/tmaiaroto/hugo-redlounge/blob/master/layouts/partials/header.html#L48
```
{{ template "_internal/google_analytics.html" . }}
```

Do I need to make a folder called _internal?
Is https://github.com/tmaiaroto/hugo-redlounge/blob/master/layouts/partials/headend.html also Google Analytics but `gaid` isn't a published param to set in either your example theme.toml, nor the README.md - which should I use?

**Comment by carsonip** [comment]
I have created a pull request to add description of Google Analytics to `README.md`. The param `gaid` works well as expected. Please see PR #38

**Comment by tmaiaroto** [comment]
Sorry was away here, thanks for the pull request. Sorry I forgot to include information about this. I didn't include a default value of course because I couldn't. It's your own specific GA ID.
