### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [tmaiaroto/hugo-redlounge#46]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37679811-1f33f176-2c93-11e8-8399-da7b69554c79.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by tzkyard** [comment]
I had  the same problem.  How can I solve this problem?
